import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

public class StreamMapExample {

	public static void main(String[] args) {
		ArrayList<String> al = new ArrayList<String>();
		al.add("Apple");
		al.add("Banana");
		al.add("PineApple");
		al.add("Orange");
		al.add("Mango");
		System.out.println("Array List:"+al);
		
		List list = al.stream()
				.map(s -> s.length())
				.collect(Collectors.toList());
		System.out.println("List generated by map:"+list);

	}

}
